### ISSUE TITLE
flag redefined: register_ttl

### ISSUE THREAD

**Issue by Leon2012** [micro/go-web#15]
```

vagrant@vagrant-ubuntu-trusty-64:/go/src/github.com/micro/go-web/examples/helloworld$ go run helloworld.go 
flag redefined: register_ttl
panic: flag redefined: register_ttl

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc4200583c0, 0xbec6e0, 0xc4200147e8, 0x97764f, 0xc, 0x97c77c, 0x17)
	/usr/local/go/src/flag/flag.go:793 +0x5e1
flag.(*FlagSet).IntVar(0xc4200583c0, 0xc4200147e8, 0x97764f, 0xc, 0x0, 0x97c77c, 0x17)
	/usr/local/go/src/flag/flag.go:592 +0x71
flag.(*FlagSet).Int(0xc4200583c0, 0x97764f, 0xc, 0x0, 0x97c77c, 0x17, 0xc)
	/usr/local/go/src/flag/flag.go:605 +0x77
github.com/micro/cli.IntFlag.Apply.func1(0x97764f, 0xc)
	/go/src/github.com/micro/cli/flag.go:417 +0xad
github.com/micro/cli.eachName(0x97764f, 0xc, 0xc420051538)
	/go/src/github.com/micro/cli/flag.go:55 +0xb2
github.com/micro/cli.IntFlag.Apply(0x97764f, 0xc, 0x0, 0x97c77c, 0x17, 0x979ba0, 0x12, 0x0, 0xc4200583c0)
	/go/src/github.com/micro/cli/flag.go:412 +0x1a2
github.com/micro/cli.(*IntFlag).Apply(0xc420054b40, 0xc4200583c0)
	<autogenerated>:1 +0x55
github.com/micro/cli.flagSet(0x0, 0x0, 0xc42009e840, 0x18, 0x2c, 0xc42007d0e0)
	/go/src/github.com/micro/cli/flag.go:46 +0x75
github.com/micro/cli.(*App).Run(0xc42009a6e0, 0xc4200101a0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/micro/cli/app.go:134 +0x6e7
github.com/micro/cli.(*App).RunAndExitOnError(0xc42009a6e0)
	/go/src/github.com/micro/cli/app.go:208 +0x53
github.com/micro/go-micro/cmd.(*cmd).Init(0xc420090370, 0x0, 0x0, 0x0, 0x17, 0xc42009e840)
	/go/src/github.com/micro/go-micro/cmd/cmd.go:434 +0xff
github.com/micro/go-web.(*service).Init(0xc42009c780, 0x0, 0x0, 0x0, 0xc42009c780, 0x85f8c7)
	/go/src/github.com/micro/go-web/service.go:292 +0x313
main.main()
	/go/src/github.com/micro/go-web/examples/helloworld/helloworld.go:22 +0xdb
exit status 2
```

**Comment by asim** [comment]
Please update your go-web code
